name: "CollectionViewAnimatedUpdatesDemo"
options:
  bundleIdPrefix: "com.huahuahu.demo"
  deploymentTarget:
    iOS: "26.0"
settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: ""
targets:
  "CollectionViewAnimatedUpdatesDemo":
    type: application
    platform: iOS
    sources:
      - "CollectionViewAnimatedUpdatesDemo"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: "com.huahuahu.demo.CollectionViewAnimatedUpdatesDemo"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
    scheme:
      testTargets:
        - "CollectionViewAnimatedUpdatesDemoTests"
  "CollectionViewAnimatedUpdatesDemoTests":
    type: bundle.unit-test
    platform: iOS
    sources:
      - "CollectionViewAnimatedUpdatesDemoTests"
    dependencies:
      - target: "CollectionViewAnimatedUpdatesDemo"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: "com.huahuahu.demo.CollectionViewAnimatedUpdatesDemoTests"
